### ISSUE TITLE
多线程内异步调用feignclient报错问题

### ISSUE THREAD

**Issue by congqian-1** [macula-projects/macula-boot#23]
### 问题描述：
如果feilcient请求是异步请求的，macula-boot-starter-feign模块的dev.macula.boot.starter.feign.interceptor.HeaderRelayInterceptor#apply方法的        ServletRequestAttributes attributes = (ServletRequestAttributes)RequestContextHolder.getRequestAttributes();获取到的attributes对象为null
 
导致返回体会包装result，导致feignclient反序列化异常，如下图：
![企业微信截图_b7978257-bf53-4076-84fd-7da46a9f888e](https://github.com/macula-projects/macula-boot/assets/35128020/e7a28974-55f2-49ff-af17-1bb7fd04bb17)

### 解决方案：
目前是显式在feign的接口定义  header，让请求头GlobalConstants.FEIGN_REQ_ID不是null
![企业微信截图_bb2308fe-d133-48ea-a301-203fa5b66e81](https://github.com/macula-projects/macula-boot/assets/35128020/e36f43b4-4e60-4e5f-8f5a-5fb2a552f7f9)

**Comment by rainsoft** [comment]
已修复
